### ISSUE TITLE
How do  define Stop Loss and Take Profit?

### ISSUE THREAD

**Issue by aliforoghi72** [Kucoin/kucoin-futures-python-sdk#19]
How do  define Stop Loss and Take Profit in kucoin-futures-python?

**Comment by facetoface10101980** [comment]
good question. I've got the same problem.
i guess you have to set Take profit with a limit order like e.g:
order_id = client.create_limit_order('XBTUSDM', 'sell', '1', '30', '45000')

so 45000 is the price. But if this price is lower than the current price i got an error.
So therefore i thought to there must be "stop price order" in this SDK but there is not. Or do i get wrong?
How can i set a "stop price order" in order to set a stop loss?

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
